### ISSUE TITLE
More unicode support

### ISSUE THREAD

**Issue by v3natio** [bamonroe/rnoweb-nvim#3]
Hey @bamonroe,great plugin. I was looking for a lua alternative to vimtex, and this was perfect since the only thing I need is the concealing functionality as everything else is done through LSP.

Anyhow, I was just wondering why there wasn't greater unicode support for characters such as ⤳ (`\leadsto`), if there wasn't a specific reason then check out the file I've attached as I've included a bunch of these characters in the format `M.sym.latex ...`. Let me know and we can work on the implementation of them. Cheers! 

[latex_unicode_mappings.txt](https://github.com/bamonroe/rnoweb-nvim/files/13278124/latex_unicode_mappings.txt)

**Comment by bamonroe** [comment]
Thanks a bunch @hooregi! There's no reason at all. Some of the characters in your txt file here I've already implemented, but I can see a bunch that I have not. Why don't you make a pull request with these added to `lua/rnoweb/symbols.lua` and I'll check it out and merge.

One thing to keep in mind is I've updated the syntax of the list. Straight substitutions like the ones in this txt file need to be double braced, e.g. `["\\curlywedge"] = {{"⋏"}}` instead of just `["\\curlywedge"] = {"⋏"}`.  I did this so I could have more programatic replacement of commands, which comes in handy for replacing diacritics like `\'a` or `\'{a}` with `á`
